app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_api:
    resource: '@AppBundle/Controller/Api'
    type: annotation

api_login_check:
    path: /api/login_check

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"